apiVersion: v1
kind: Pod
metadata:
  name: nginx-glusterfs
  labels:
    name: nginxrep
    file: glusterfs
spec:
  containers:
    - name: web
      image: fedora/nginx
      privileged: true
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          - name: myglusterfs
            mountPath: "/usr/share/nginx/html/test"
  volumes:
    - name: myglusterfs
      glusterfs:
        endpoints: "glusterfs-cluster"
        path: "MyVolume"
        readOnly: false
