apiVersion: v1
kind: Pod
metadata:
  name: nginx-local
  labels:
    name: nginxrep
    file: local
spec:
  containers:
    - name: nginx-local
      image: fedora/nginx
      privileged: true
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          - name: mylocalserver
            mountPath: "/usr/share/nginx/html/test"
  volumes:
    - name: mylocalserver
      hostPath:
        path: "/opt/data"
