apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - image: tutum/mysql
      name: mysql
      volumeMounts:
        - name: mysql-ceph
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-ceph
      rbd: 
        monitors: 
          - 192.168.58.16:6789
        pool: rbd
        image: foo
        user: admin
        secretRef: 
          name: ceph-secret
        fsType: ext4
        readOnly: false

